# Generated by Django 4.2 on 2023-04-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=255)),
                ('Total_Confirmed_Cases', models.CharField(max_length=255)),
                ('Total_Deaths_Cases', models.CharField(max_length=255)),
                ('Total_Recovered_Cases', models.CharField(max_length=255)),
                ('Date', models.DateField()),
            ],
        ),
    ]
